#!/bin/bash
cargo fmt
cargo lint
cargo build
rm -r ./target/doc/
cargo docs
cargo doc-tests
cargo tests
# GitHub pages is looking for index.html in the root dir, so let's redirect it
echo "<meta http-equiv=\"refresh\" content=\"0; url=csshw_lib/index.html\">" > target/doc/index.html
cp -r target/doc/* ./docs/