[package]
name = "csshw"
version = "0.7.0"
edition = "2021"
license-file = "LICENSE.txt"
default-run = "csshw"

[[bin]]
name = "csshw"
path = "src/main.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "3.1.12", features = ["derive"] }
os_info = { version="3.7.0", default-features = false }
rmp = "0.8.11"
serde = "1.0.163"
serde_derive = "1.0.163"
ssh2-config = "0.1.6"
tokio = { version = "1.26.0", features = ["rt", "rt-multi-thread", "net", "sync", "macros", "time", "signal", "process"] }

[dependencies.confy]
version = "0.5.1"
features = ["toml_conf"]
default-features = false

[dependencies.windows]
version = "0.44.0"
features = [
    "Win32_Foundation",
    "Win32_Security",
    "Win32_System_Console",
    "Win32_System_Threading",
    "Win32_UI_WindowsAndMessaging",
    "Win32_UI_Shell",
    "Win32_UI_Shell_Common",
    "Win32_Graphics_Gdi",
    "Win32_System_LibraryLoader",
    "Win32_Graphics_Dwm",
    "Win32_UI_Input_KeyboardAndMouse",
]

[build-dependencies]
embed-resource = "2.2"
