#
#   csshw CI with Coverage
#
# Only runs on pull requests to the main branch.
# Uses the shared CI workflow with coverage collection enabled.
# Posts detailed coverage reports as PR comments and uploads HTML artifacts.

name: CI with Coverage

on:
  pull_request:
    branches: [ "main" ]
    paths:
      - .cargo/**
      - .github/workflows/ci-coverage.yml
      - .github/workflows/ci.yml
      - .github/workflows/_shared-ci.yml
      - src/**
      - build.rs
      - Cargo.toml
      - clippy.toml
      - Makefile.toml
      - rustfmt.toml

jobs:
  ci-with-coverage:
    uses: ./.github/workflows/_shared-ci.yml
    with:
      run_coverage: true

  coverage-report:
    runs-on: ubuntu-latest
    needs: ci-with-coverage
    if: always() && needs.ci-with-coverage.result == 'success'
    steps:
    - uses: actions/checkout@v5

    - name: Download Coverage XML Data
      uses: actions/download-artifact@v4
      with:
        name: coverage-xml-data
        path: coverage-data/

    - name: Generate Code Coverage Summary
      uses: irongut/CodeCoverageSummary@v1
      with:
        filename: coverage-data/coverage.xml
        badge: true
        fail_below_min: false
        format: markdown
        hide_branch_rate: false
        hide_complexity: true
        indicators: false
        output: both
        thresholds: '50 80'

    # Post coverage comment to PR
    - name: Add Coverage PR Comment
      uses: marocchino/sticky-pull-request-comment@v2
      if: github.event_name == 'pull_request'
      with:
        recreate: true
        path: code-coverage-results.md
