name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: windows-latest
    env:
      RUST_VERSION: 1.88.0
    steps:
    - uses: actions/checkout@v3
    - name: Configure correct rust version
      run: rustup update $RUST_VERSION && rustup default $RUST_VERSION
    - name: Check format
      run: cargo fmt -- --check
    - name: Run linter
      run: cargo lint
    - name: Build
      run: cargo build --verbose
    - name: Build docs
      run: cargo docs
    - name: Run tests docs
      run: cargo doc-tests
    - name: Run tests all
      run: cargo tests
