#
#   csshw CI
#
# Only runs on the main branch on pushes.
# For pull requests, see ci-coverage.yml which includes coverage reporting.
# Uses the shared CI workflow without coverage collection.

name: CI

on:
  push:
    branches: [ "main" ]
    paths:
      # NOTE: Keep this list in sync with ci-coverage.yml
      - .cargo/**
      - .github/workflows/ci-coverage.yml
      - .github/workflows/ci.yml
      - .github/workflows/_shared-ci.yml
      - src/**
      - build.rs
      - Cargo.toml
      - clippy.toml
      - Makefile.toml
      - rustfmt.toml

jobs:
  ci:
    uses: ./.github/workflows/_shared-ci.yml
    with:
      run_coverage: false
